[package]
name = "riboprof-tools"
version = "0.1.0"
authors = ["Nicholas Ingolia <ingolia@berkeley.edu>"]
edition = '2015'

[dependencies]
bio = "0.23"
rust-htslib = "0.21.0"
itertools = "0.7.8"
csv = "1.0.2"
failure = "0.1.2"
clap = "2.32.0"
regex = "1"
bio-types = "*"

[profile.dev]
opt-level = 3

[lib]
name = "riboprof"
path = "src/riboprof/lib.rs"

[[bin]]
name = "fastx-split"
path = "src/fastx_split_main.rs"

[[bin]]
name = "fp-framing"
path = "src/fp_framing_main.rs"

[[bin]]
name = "bam-suppress-duplicates"
path = "src/bam_suppress_duplicates.rs"
